
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "cpic"
version = "0.1.0"
description = "Compressed Predictive Information Coding"
readme = "README.md"
requires-python = ">=3.10"
authors = [
    { name = "Rui Meng", email = "mengrui6351@gmail.com" }
]
maintainers = [
    { name = "Phoenix Pham", email = "phoenixpham@berkeley.edu" }
    { name = "Kailin Zhuang", email = "kailin.zhuang@berkeley.edu" },
    { name = "Aditya Anantaraman", email = "aditya.anant@berkeley.edu"}
]
license = { file = "LICENSE.txt" }
dependencies = [
  "numpy>=1.19.5",
  "tensorboard>=2.20.0",
  "scipy",
  "h5py",
  "pandas",
  "scikit-learn",
  "matplotlib",
  "torch",
  "torchvision",
  "tensorboardX",
  "tqdm",
  "sdepy",
  "notebook",
]

[project.optional-dependencies]
dca = [
  "DynamicalComponentsAnalysis",
  "numpy>=1.19.5,<2",
]
video = [
  "opencv-python-headless>=4.8",
]
dev = [
  "pytest",
]

[project.urls]
Homepage = "https://github.com/BouchardLab/CPIC_dev"

[tool.hatch.build.targets.wheel]
packages = ["src/cpic"]

[tool.uv]
dev-dependencies = [
  "pytest",
]
